import React, { useState } from "react";
import { Link } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import Layout from '../components/Layout';
import { logout } from '../features/authSlice';
import { updateAgendamento } from '../features/dataSlice';

export default function AdminPage() {
  const [tab, setTab] = useState('denuncias');
  const { lojas, denuncias } = useSelector((state) => state.data);
  const dispatch = useDispatch();
  return <Layout><header className="bg-black text-white p-3 rounded mb-3 text-center position-relative"><Link to="/" className="position-absolute start-0 top-50 translate-middle-y ms-3 text-white"><i className="fa-solid fa-arrow-left" /></Link><h2 className="mb-0">ADMINISTRAÇÃO</h2><small className="text-light">Painel de Controle Central</small></header><div className="card p-3 mb-3"><div className="row g-2 mb-3"><div className="col-6"><div className="admin-kpi-card"><h3>{lojas.length}</h3><p>Lojas</p></div></div><div className="col-6"><div className="admin-kpi-card"><h3>{denuncias.length}</h3><p>Denúncias</p></div></div></div><div className="d-flex gap-2 mb-3"><button className={`btn btn-outline-dark w-100 admin-tab-btn ${tab==='denuncias'?'active':''}`} onClick={()=>setTab('denuncias')}>Denúncias</button><button className={`btn btn-outline-dark w-100 admin-tab-btn ${tab==='lojas'?'active':''}`} onClick={()=>setTab('lojas')}>Gestão de Lojas</button></div>{tab==='denuncias' ? <div><h5 className="mb-3">Denúncias Recentes</h5><div className="d-flex flex-column gap-3">{denuncias.map((d)=><div key={d.id} className="admin-list-item"><div className="d-flex justify-content-between"><span className="admin-badge badge-danger">Denúncia #{d.id}</span><small className="text-muted">{d.data}</small></div><h6 className="mt-2">{d.lojaNome}</h6><p className="small text-muted mb-1"><strong>Motivos:</strong> {d.motivos.join(', ')}</p><p className="small bg-light p-2 rounded border-start border-danger">"{d.descricao}"</p><div className="d-flex gap-2 mt-2"><button className="btn btn-sm btn-ignore w-100">Ignorar</button><button className="btn btn-sm btn-ban w-100">Suspender</button></div></div>)}</div></div> : <div><h5 className="mb-3">Lojas Registradas</h5><div className="d-flex flex-column gap-3">{lojas.map((loja)=><div key={loja.id} className="admin-list-item"><span className="admin-badge badge-info">ID: {loja.id}</span><h6 className="mt-2">{loja.nome}</h6><p className="small text-muted mb-1"><i className="fa-solid fa-star text-warning" /> {loja.media} ({loja.quantidadeAvaliacoes})</p><p className="small text-muted"><i className="fa-solid fa-tags" /> {loja.tags.length} serviços</p><button className="btn btn-sm btn-ban w-100">Bloquear Loja</button></div>)}</div></div>}<button className="btn btn-outline-secondary w-100 mt-3" onClick={()=>dispatch(logout())}>Sair</button></div></Layout>;
}
